### ISSUE TITLE
memsql/cluster-in-a-box latest image failed to start container

### ISSUE THREAD

**Issue by ntedgi** [memsql/deployment-docker#3]
after pulling the latest image this issue occurs 

```
    ~/workdir/js/master *16 !1 ▓▒░ docker-compose up  memsql                                                            ░▒▓ 2 ✘  15s   2.7.2   08:24:30 
    Recreating platform-js_memsql_1 ... done
    Attaching to platform-js_memsql_1
    memsql_1           | 2021-07-26 05:24:41.431505 Starting Cluster
    memsql_1           | Latest errors from MemSQL tracelog:
    memsql_1           | 13651863 2021-07-26 05:24:55.333  FATAL: Thread 115111: jumpToUpgradeStep: This node is not managed by a supported tool. Please use a toolbox version at least as new as 1.11.3.
    memsql_1           | : Failed to connect to MemSQL: process exited: exit status 1
    memsql_1           | Traceback (most recent call last):
    memsql_1           |   File "/startup", line 122, in <module>
    memsql_1           |     start_cluster()
    memsql_1           |   File "/startup", line 86, in start_cluster
    memsql_1           |     ctl("start-node", "--all")
    memsql_1           |   File "/startup", line 18, in ctl
    memsql_1           |     subprocess.check_output(["memsqlctl", "-yj"] + list(args)))
    memsql_1           |   File "/usr/lib64/python2.7/subprocess.py", line 575, in check_output
    memsql_1           |     raise CalledProcessError(retcode, cmd, output=output)
    memsql_1           | subprocess.CalledProcessError: Command '['memsqlctl', '-yj', 'start-node', '--all']' returned non-zero exit status 1
```
on this version everything works fine `memsql/cluster-in-a-box:centos-7.3.12-2d93725f98-3.2.11-1.11.7`

this is my docker-compose setup  using [memsql/cluster-in-a-box
][1]
 
      memsql:
        image: memsql/cluster-in-a-box
        volumes:
          - "./init.sql"
        ports:
          - "3307:3306"
          - "8080:8080"
        environment:
          START_AFTER_INIT: Y
          ROOT_PASSWORD: 'root'
          LICENSE_KEY:*************************

'Please use a toolbox version at least as new as 1.11.3.'

OS: macOs bigSur v11.4
Docker : v20.10.7

  [1]: https://hub.docker.com/r/memsql/cluster-in-a-box

**Comment by volodymyr-memsql** [comment]
Have you tried creating and running the container with `docker` (not docker-compose)?
I did the following:
```
$ docker pull memsql/cluster-in-a-box:latest
$ docker run -i --init --name ciab3 -e LICENSE_KEY=$LICENSE -e ROOT_PASSWORD=pass -p 3310:3306 -p 8080:8080 memsql/cluster-in-a-box:latest
$ docker start ciab3

```
Everything works:
```
2021-07-27 16:03:56.755398 Initializing SingleStore Cluster in a Box
2021-07-27 16:03:56.755600 Creating...
2021-07-27 16:03:57.903604 Done.
2021-07-27 16:03:57.903668 Configuring...
2021-07-27 16:03:59.140822 Done.
2021-07-27 16:03:59.140879 Bootstrapping...
2021-07-27 16:04:06.267689 Done.
2021-07-27 16:04:06.267851 Configuring Toolbox...
2021-07-27 16:04:06.356895 Done.
```

I connected to the docker (`docker exec -it ciab3 bash`) and checked versions:
```
$ memsql-admin version
Version: 1.11.9
Commit: 3b3c95e959a36bcfb34d89a75f3f80c3b6b4d326
$ memsql-admin list-nodes
+------------+--------+-----------+------+---------------+--------------+---------+----------------+--------------------+--------------+
| MemSQL ID  |  Role  |   Host    | Port | Process State | Connectable? | Version | Recovery State | Availability Group | Bind Address |
+------------+--------+-----------+------+---------------+--------------+---------+----------------+--------------------+--------------+
| 38D05368ED | Master | 127.0.0.1 | 3306 | Running       | True         | 7.5.6   | Online         |                    | 0.0.0.0      |
| 89F91C1B00 | Leaf   | 127.0.0.1 | 3307 | Running       | True         | 7.5.6   | Online         | 1                  | 0.0.0.0      |
+------------+--------+-----------+------+---------------+--------------+---------+----------------+--------------------+--------------+
```

**Comment by mshcherbina** [comment]
@ntedgi Thank you for filing the issue! 
For upgrades from 7.0 and newer versions, the workaround is to update the toolbox_version variable. This can be done in two ways:
1. Run `sdb-admin update-config --key toolbox_version --value 1.11.7 --all` from the running container, right before changing the image to 7.5.
2. Manually update the memsql.cnf files for each node adding `toolbox_version=1.11.7` line to the file content.  The config file for a node is located under node's directory in ./init.sql.
