### ISSUE TITLE
failed to start container

### ISSUE THREAD

**Issue by nojvek** [memsql/deployment-docker#6]
I'm getting this error on latest container after I ran docker pull to upgrade from 7.6 to 7.8

```
memsql_1  | 2022-05-18 05:46:50.471113 Starting Cluster
memsql_1  | Latest errors from the database's tracelog:
memsql_1  | 04352817 2022-05-18 05:46:55.429  FATAL: Thread 115121: jumpToUpgradeStep: This node is not managed by a supported tool. Please use a toolbox version at least as new as 1.11.3.
memsql_1  | : Failed to connect to the database: process exited: exit status 1
memsql_1  | Traceback (most recent call last):
memsql_1  |   File "/startup", line 136, in <module>
memsql_1  |     start_cluster()
memsql_1  |   File "/startup", line 100, in start_cluster
memsql_1  |     ctl("start-node", "--all")
memsql_1  |   File "/startup", line 18, in ctl
memsql_1  |     subprocess.check_output(["memsqlctl", "-yj"] + list(args)))
memsql_1  |   File "/usr/lib64/python3.9/subprocess.py", line 424, in check_output
memsql_1  |     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
memsql_1  |   File "/usr/lib64/python3.9/subprocess.py", line 528, in run
memsql_1  |     raise CalledProcessError(retcode, process.args,
memsql_1  | subprocess.CalledProcessError: Command '['memsqlctl', '-yj', 'start-node', '--all']' returned non-zero exit status 1.
ss_dcompose_memsql_1 exited with code 1
```

**Comment by volodymyr-memsql** [comment]
@nojvek, could you please share commands that you run to get the error?
